CREATE TABLE file_metadata (
    uuid UUID NOT NULL,
    description VARCHAR(255),
    file_path VARCHAR(255),
    uploaded_by VARCHAR(255),
    verified BOOLEAN,
    author VARCHAR(255) NOT NULL,
    rating DOUBLE PRECISION DEFAULT 0 NOT NULL,
    CONSTRAINT file_metadata_pkey PRIMARY KEY (uuid)
);

CREATE TABLE rates_collection (
    uuid UUID NOT NULL,
    value INTEGER,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT rates_collection_pkey PRIMARY KEY (uuid, name)
);

CREATE TABLE resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    parent_uuid UUID,
    name VARCHAR(255),
    type VARCHAR(255),
    read_only BOOLEAN,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT resources_type_check CHECK (type IN ('FOLDER', 'FILE'))
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    role SMALLINT,
    bookmarks UUID[],
    CONSTRAINT users_role_check CHECK (role >= 0 AND role <= 2)
);

-- We do this after table creation to ensure the referenced tables exist
ALTER TABLE rates_collection
    ADD CONSTRAINT fk_rates_file_metadata
    FOREIGN KEY (uuid) REFERENCES file_metadata(uuid);